### ISSUE TITLE
openjazz.000 is a blob

### ISSUE THREAD

**Issue by fabiangreffrath** [AlisterT/openjazz#35]
I know that the `openjazz.000` file contains the OpenJazz logo for use in the menu. However, it is still a binary file with no sources. Since the logo is now provided in `unix/OpenJazz.png` it would be nice if a reproduction rule for the `openjazz.000` file could be added to the Makefile(s).

**Comment by carstene1ns** [comment]
Unfortunately this would involve a generator script or program because of the file format, i.e. need to make sure `perl`/`python`/`ruby`/etc. is available or compile some C sources beforehand, which will get messy for cross-compilation.
What bugs me the most about this file is that it needs to be piggy-backed all the time.
I have a local branch where I just moved it into a header file (using `xxd`). Would this be an okay-ish solution?

**Comment by fabiangreffrath** [comment]
Yes, this would be a bit "cleaner". At least, it would by possible to apply a proper Copyright blurb to the header file and include a comment about what the contents of that file mean and where it originates from.

I have done something similar in one of my own projects:
https://github.com/fabiangreffrath/crispy-doom/commit/c4f82f1828da23bc7e8b2b48ed45b052a4010951
