### ISSUE TITLE
Monkeys in Holidaius fly

### ISSUE THREAD

**Issue by happygreenfrog** [AlisterT/openjazz#47]
I think this screenshot speaks for itself, honestly: ![image](https://user-images.githubusercontent.com/41273098/42739285-3f3da94e-885a-11e8-9176-8288b7829e3d.png)

To put it into words, however: For some odd reason, the monkeys in Holidaius float above the ground, instead of walking across it like they're supposed to. This sometimes makes the level a lot harder than it's supposed to be, since you have to jump in order to shoot at them.

**Comment by carstene1ns** [comment]
Apparently the monkey event animation has different offset defined: `left = 28`, `right = 50`.
While this seems to be very seldom (at least I did not find other events with a quick glance), there was already a special treatment in the code. However, it incorrectly used the right offset, when it really should have used the left.
While I was at it, I changed another special handling, which seemed the right thing to do. Could not verify this was wrong, because all events i found did have the same offsets.
