### ISSUE TITLE
Version 20231028 Issues

### ISSUE THREAD

**Issue by vicokoby** [AlisterT/openjazz#98]
**Issues**
- There is no sound in the game
- Scaling options are not available

**Environment**
- Windows 10 Pro x64
- OpenJazz 20231028 win64
- Jazz 1.3
- Screen resolution: 1366x768
- Soundcard: Realtek High Definition Audio

Please note that these issues do not occur in version 20190106.

**Comment by carstene1ns** [comment]
Can you try changing the audio driver? I have read that the current default in SDL2 (wasapi) causes issues sometimes.

To do it temporarily we can set an environment variable:
<kbd>Windows Key</kbd> + <kbd>R</kbd>
Enter `cmd`, press <kbd>Enter</kbd>.

In the command prompt:
```cmd
cd C:/Users/YourName/Desktop/OJ
set SDL_AUDIODRIVER="directsound"
OpenJazz.exe
```

---

Scaling is currently disabled for SDL2 builds, since I need to rewrite that part of the code.

**Comment by vicokoby** [comment]
I tried setting the environment variable: SDL_AUDIODRIVER="directsound" but even then there is no sound in the game.

**Comment by Apaczer** [comment]
@carstene1ns, seems like SDL2 issue (works fine on SDL1) for MinGW builds. No issue when running through VM on UNIX system with both setups.

**Comment by carstene1ns** [comment]
@vicokoby: If you have the time, can you test this build? [OpenJazz-win32-sdl2-audiofix.zip](https://github.com/AlisterT/openjazz/files/13222993/OpenJazz-win32-sdl2-audiofix.zip)

**Comment by vicokoby** [comment]
> @vicokoby: If you have the time, can you test this build? [OpenJazz-win32-sdl2-audiofix.zip](https://github.com/AlisterT/openjazz/files/13222993/OpenJazz-win32-sdl2-audiofix.zip)
The fix is working on my computer. Thank you
